apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-svc
spec:
  ports:
  - port: {{ .Values.backstage_port.reverse_port }}
    targetPort: {{ .Values.backstage_port.http }}
  selector:
    app: nginx-deploy