apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: {{ .Values.backstage_replica.count }}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: {{ .Values.backstage_image.repository }}:{{ .Values.backstage_image.tag }}
        ports:
          - containerPort: 80